{% set name = "pip-audit" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pip_audit-{{ version }}.tar.gz
  sha256: 6431c363efa80ef52c2599197c5b8a39ff8708ce316624b97fa35b5cdf493118

build:
  number: 0
  noarch: python
  entry_points:
    - pip-audit = pip_audit._cli:audit
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7
    - cachecontrol >=0.12.10
    - cyclonedx-python-lib >=2.0,<3.dev0,!=2.5.0
    - html5lib >=1.1
    - packaging >=23.0.0
    - pip-api >=0.0.28
    - pip-requirements-parser >=32.0.0
    - rich >=12.4
    - toml >=0.10

test:
  imports:
    - pip_audit
  commands:
    - pip check
    - pip-audit --help
  requires:
    - pip

about:
  home: https://github.com/trailofbits/pip-audit
  summary: A tool for scanning Python environments for known vulnerabilities
  license: Apache-2.0
  license_file: LICENSE
  description: |
    `pip-audit` is a tool for scanning Python environments for packages
    with known vulnerabilities. It uses the Python Packaging Advisory Database
    (https://github.com/pypa/advisory-db) via the
    [PyPI JSON API](https://warehouse.pypa.io/api-reference/json.html) as a source
    of vulnerability reports.

    This project is developed by [Trail of Bits](https://www.trailofbits.com/) with
    support from Google. This is not an official Google product.

    **Features**

    - Support for auditing local environments and requirements-style files
    - Support for multiple vulnerability services
      ([PyPI](https://warehouse.pypa.io/api-reference/json.html#known-vulnerabilities),
      [OSV](https://osv.dev/docs/))
    - Support for emitting
      [SBOMs](https://en.wikipedia.org/wiki/Software_bill_of_materials) in
      [CycloneDX](https://cyclonedx.org/) XML or JSON
    - Human and machine-readable output formats (columnar, JSON)
    - Seamlessly reuses your existing local `pip` caches
  doc_url: https://github.com/trailofbits/pip-audit
  dev_url: https://github.com/trailofbits/pip-audit

extra:
  recipe-maintainers:
    - sugatoray
